In [1]:
import pandas as pd
import numpy as np

In [2]:
y = np.loadtxt('evaluations/federated_learning/clusters.csv', delimiter=',').astype(int)
num_clusters = 6
cluster_users = {i: [] for i in range(num_clusters)}

# Iterate through each cluster
for cluster_number in range(num_clusters):
    users_in_cluster = np.where(y == cluster_number)[0] +1
    cluster_users[cluster_number] = users_in_cluster
    
cluster_users

{0: array([14], dtype=int64),
 1: array([ 1,  2,  4,  6,  7, 10, 11, 16, 20, 21, 22, 23, 24, 25, 26, 28, 30],
       dtype=int64),
 2: array([ 3,  8, 12, 17, 19, 27], dtype=int64),
 3: array([ 9, 29], dtype=int64),
 4: array([ 5, 15], dtype=int64),
 5: array([13, 18], dtype=int64)}

In [15]:
dense_results = pd.read_csv('evaluations/clustered_federated_learning/TopK_BiLSTM_MoE.csv')
dense_results

,Unnamed: 0,architecture,train_time,avg_time_epoch,mse,mse_std,rmse,rmse_std,mape,mape_std,mae,mae_std
0,0,Dense_MoE_e4d8_d16,10.447563,0.504483,0.034487,0.000565,0.185704,0.001521,4.599660e+04,5437.107706,0.124994,0.004148
1,1,Dense_MoE_e4d8_d16,7.408247,0.539574,0.017630,0.000786,0.132757,0.002950,2.356738e+05,14758.242472,0.076916,0.001365
2,2,Dense_MoE_e4d8_d16,7.009502,0.545607,0.020110,0.000204,0.141809,0.000721,6.149872e+04,7142.270860,0.078914,0.000349
3,3,Dense_MoE_e4d8_d16,6.917985,0.525322,0.022317,0.000517,0.149381,0.001735,1.202021e+05,22875.208008,0.063792,0.001033
4,4,Dense_MoE_e4d8_d16,7.491158,0.529121,0.013521,0.000223,0.116276,0.000961,7.663751e+04,6957.332706,0.077471,0.002490
...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,TopK_BiLSTM_MoE,26.224467,1.862473,0.023597,0.000404,0.153608,0.001318,6.126678e+04,10238.224182,0.095104,0.001226
116,116,TopK_BiLSTM_MoE,32.797880,2.386674,0.019403,0.000391,0.139288,0.001407,2.278528e+05,36882.574679,0.093905,0.002270
117,117,TopK_BiLSTM_MoE,28.105699,1.868839,0.011016,0.000190,0.104956,0.000902,5.096430e+04,7410.250454,0.045663,0.002687
118,118,TopK_BiLSTM_MoE,36.866484,2.454391,0.017128,0.000738,0.130854,0.002834,4.408406e+05,32113.625968,0.090236,0.001258
119,119,TopK_BiLSTM_MoE,27.220208,1.893071,0.017471,0.000398,0.132171,0.001503,1.428982e+06,100520.941343,0.081650,0.000393

In [3]:
df_evaluation = dense_results[0:30]

df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
moe_1 = df_results
df_results

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [4]:
df_evaluation = pd.read_csv('evaluations/clustered_federated_learning/TopK_Dense_MoE.csv')

df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
moe_2 = df_results
df_results

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [5]:
df_evaluation = pd.read_csv('evaluations/clustered_federated_learning/Soft_BiLSTM_MoE.csv')

df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
moe_3 = df_results
df_results

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [6]:
df_evaluation = pd.read_csv('evaluations/clustered_federated_learning/TopK_BiLSTM_MoE.csv')

df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
moe_4 = df_results
df_results

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [7]:
# Results

In [8]:
print("Mean mse: ", moe_1["mse"].mean())
moe_1

Mean mse:  0.018929298784003453

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [9]:
print("Mean mse: ", moe_2["mse"].mean())
moe_2

Mean mse:  0.018929298784003453

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [10]:
print("Mean mse: ", moe_3["mse"].mean())
moe_3

Mean mse:  0.018929298784003453

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498

In [11]:
print("Mean mse: ", moe_4["mse"].mean())
moe_4

Mean mse:  0.018929298784003453

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,Dense_MoE_e4d8_d16,9.537452,0.022925,0.151403,231102.265625,0.104332
1,cluster_1,Dense_MoE_e4d8_d16,8.594780,0.019537,0.137268,292778.242743,0.085262
2,cluster_2,Dense_MoE_e4d8_d16,8.239971,0.018079,0.133207,100470.966363,0.083444
3,cluster_3,Dense_MoE_e4d8_d16,9.674631,0.023710,0.152888,155249.099630,0.097578
4,cluster_4,Dense_MoE_e4d8_d16,9.022963,0.011767,0.108173,90076.578125,0.065834
5,cluster_5,Dense_MoE_e4d8_d16,7.524832,0.017556,0.132232,80454.428711,0.085498