In [15]:
import pandas as pd
import numpy as np

In [2]:
dense_results = pd.read_csv('evaluations/local_learning/LSTM_benchmark.csv')
dense_results

,Unnamed: 0,architecture,train_time,avg_time_epoch,mse,mse_std,rmse,rmse_std,mape,mape_std,mae,mae_std
0,0,L3_U16,9.349461,0.377300,0.034101,0.001172,0.184646,0.003174,7.684803e+04,76368.551047,0.128049,0.003624
1,1,L3_U16,6.901573,0.381778,0.017999,0.000795,0.134140,0.002948,1.563642e+05,19373.125474,0.078911,0.003110
2,2,L3_U16,9.861912,0.370500,0.021385,0.000986,0.146210,0.003351,5.275009e+04,27010.966959,0.083458,0.003016
3,3,L3_U16,12.407765,0.375891,0.022548,0.000398,0.150155,0.001323,1.323894e+05,10105.458214,0.065013,0.000794
4,4,L3_U16,8.969604,0.378942,0.014485,0.000220,0.120351,0.000911,1.006256e+05,8686.180798,0.077778,0.003253
...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,L2_U20,53.499830,2.639695,0.030621,0.003712,0.174779,0.010494,1.177978e+05,38501.550518,0.110774,0.009411
176,176,L2_U20,109.373161,2.498577,0.020880,0.000204,0.144498,0.000706,1.224330e+05,5239.017740,0.103547,0.000877
177,177,L2_U20,68.815570,2.540393,0.010702,0.000358,0.103442,0.001724,5.429569e+04,13804.586163,0.046831,0.004418
178,178,L2_U20,56.531725,2.599237,0.020039,0.002462,0.141384,0.008588,5.313414e+05,78721.016695,0.100944,0.003674
179,179,L2_U20,61.471449,2.553378,0.019009,0.000366,0.137867,0.001324,1.025715e+06,119481.185859,0.087026,0.004663

In [16]:

y = np.loadtxt('evaluations/federated_learning/clusters.csv', delimiter=',').astype(int)
num_clusters = 6
cluster_users = {i: [] for i in range(num_clusters)}

# Iterate through each cluster
for cluster_number in range(num_clusters):
    users_in_cluster = np.where(y == cluster_number)[0] +1
    cluster_users[cluster_number] = users_in_cluster
    
cluster_users

{0: array([14], dtype=int64),
 1: array([ 1,  2,  4,  6,  7, 10, 11, 16, 20, 21, 22, 23, 24, 25, 26, 28, 30],
       dtype=int64),
 2: array([ 3,  8, 12, 17, 19, 27], dtype=int64),
 3: array([ 9, 29], dtype=int64),
 4: array([ 5, 15], dtype=int64),
 5: array([13, 18], dtype=int64)}

In [64]:
df_evaluation

,Unnamed: 0,architecture,train_time,avg_time_epoch,mse,mse_std,rmse,rmse_std,mape,mape_std,mae,mae_std
0,0,L3_U16,9.349461,0.377300,0.034101,0.001172,0.184646,0.003174,7.684803e+04,76368.551047,0.128049,0.003624
1,1,L3_U16,6.901573,0.381778,0.017999,0.000795,0.134140,0.002948,1.563642e+05,19373.125474,0.078911,0.003110
2,2,L3_U16,9.861912,0.370500,0.021385,0.000986,0.146210,0.003351,5.275009e+04,27010.966959,0.083458,0.003016
3,3,L3_U16,12.407765,0.375891,0.022548,0.000398,0.150155,0.001323,1.323894e+05,10105.458214,0.065013,0.000794
4,4,L3_U16,8.969604,0.378942,0.014485,0.000220,0.120351,0.000911,1.006256e+05,8686.180798,0.077778,0.003253
5,5,L3_U16,13.057678,0.372270,0.021100,0.000497,0.145250,0.001717,1.165001e+05,6149.822226,0.107371,0.004686
6,6,L3_U16,10.403571,0.386939,0.019965,0.000945,0.141272,0.003361,1.053466e+05,48754.699141,0.084409,0.002921
7,7,L3_U16,10.103720,0.379343,0.025551,0.002042,0.159760,0.006381,5.354276e+04,59583.496376,0.104124,0.000494
8,8,L3_U16,6.329050,0.392077,0.033212,0.003345,0.182083,0.009321,6.730265e+01,2.629975,0.105375,0.005952
9,9,L3_U16,8.440792,0.379335,0.014420,0.000237,0.120079,0.000989,2.276763e+06,154656.405769,0.073058,0.001570
10,10,L3_U16,9.830601,0.387043,0.014753,0.000858,0.121429,0.003560,6.032808e+04,22864.914026,0.078742,0.002531
11,11,L3_U16,9.649450,0.368760,0.011462,0.001685,0.106861,0.008026,1.165793e+05,28971.805609,0.077667,0.007598
12,12,L3_U16,8.296115,0.352497,0.018813,0.000615,0.137149,0.002238,8.816124e+04,35141.154198,0.087775,0.001138
13,13,L3_U16,11.394103,0.359958,0.020717,0.000769,0.143919,0.002678,1.062954e+05,9618.214916,0.097922,0.003994
14,14,L3_U16,10.381031,0.357419,0.009730,0.000228,0.098638,0.001158,1.080315e+05,20976.061961,0.055635,0.002087
15,15,L3_U16,7.716461,0.362908,0.013514,0.000083,0.116251,0.000355,7.675874e+04,9386.134985,0.072822,0.002394
16,16,L3_U16,9.623360,0.360006,0.017830,0.000136,0.133527,0.000508,2.060066e+05,61454.989123,0.090104,0.002568
17,17,L3_U16,8.910417,0.361563,0.014546,0.000253,0.120604,0.001051,1.051751e+05,4941.623475,0.078159,0.002166
18,18,L3_U16,10.234080,0.376036,0.014277,0.000300,0.119482,0.001255,6.766236e+04,18488.818428,0.067559,0.002511
19,19,L3_U16,10.155075,0.363233,0.034737,0.004696,0.186090,0.012728,2.566929e+05,52062.891549,0.143860,0.013383
20,20,L3_U16,10.099820,0.359731,0.017566,0.000216,0.132535,0.000815,1.037026e+05,4954.911647,0.098626,0.001575
21,21,L3_U16,8.230838,0.388783,0.020476,0.000661,0.143081,0.002313,8.343171e+04,33385.713360,0.088240,0.002233
22,22,L3_U16,7.069914,0.382311,0.010457,0.000907,0.102197,0.004392,1.697104e+05,44852.366968,0.066864,0.008289
23,23,L3_U16,12.704322,0.361095,0.008168,0.000417,0.090358,0.002314,1.628955e+05,24351.145484,0.063889,0.002790
24,24,L3_U16,6.501902,0.371647,0.021787,0.000238,0.147602,0.000807,5.018099e+04,28015.566007,0.093256,0.006474
25,25,L3_U16,10.194347,0.369221,0.024807,0.000113,0.157502,0.000358,1.435295e+05,52968.260620,0.105892,0.008846
26,26,L3_U16,8.031771,0.362183,0.020181,0.001320,0.142008,0.004686,1.983182e+05,46157.044539,0.099678,0.002711
27,27,L3_U16,8.340387,0.376061,0.011463,0.000321,0.107056,0.001495,4.919600e+04,6685.710473,0.045771,0.000309
28,28,L3_U16,8.413336,0.361718,0.018306,0.000327,0.135294,0.001210,4.620812e+05,149492.925594,0.095224,0.001595
29,29,L3_U16,16.855101,0.363952,0.016761,0.001094,0.129418,0.004249,1.607004e+06,360815.585860,0.080609,0.002624

In [68]:
df_evaluation = dense_results[0:30]
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
model_1 = df_results
df_results

,cluster,architecture,time,mse,rmse,mape,mae
0,cluster_0,L3_U16,11.394103,0.020717,0.143919,106295.427083,0.097922
1,cluster_1,L3_U16,9.897624,0.019095,0.135827,331037.733150,0.086787
2,cluster_2,L3_U16,9.584049,0.018448,0.134641,115809.873379,0.087098
3,cluster_3,L3_U16,7.371193,0.025759,0.158689,231074.245075,0.100300
4,cluster_4,L3_U16,9.675317,0.012108,0.109495,104328.515625,0.066706
5,cluster_5,L3_U16,8.603266,0.016680,0.128877,96668.179688,0.082967

In [69]:
df_evaluation = dense_results[30:60]
df_evaluation.reset_index(inplace=True)
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
model_2 = df_results
df_results

KeyError: 0

In [8]:
df_evaluation = dense_results[60:90]
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
df_results

Architecture:  L3_U16
Mean train time epoch:  0.3713500199651108
Mean mse:  0.018837226792756005
Mean mae:  0.08652798487908304

In [9]:
df_evaluation = dense_results[90:120]
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
df_results

Architecture:  L1_U4
Mean train time epoch:  0.27903444980955355
Mean mse:  0.019642803771421257
Mean mae:  0.08932139645848004

In [10]:
df_evaluation = dense_results[120:150]
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
df_results

Architecture:  L5_U32
Mean train time epoch:  0.49517649904781524
Mean mse:  0.018962936124039976
Mean mae:  0.0862361127717627

In [11]:
df_evaluation = dense_results[150:180]
df_results = pd.DataFrame(columns=["cluster", "architecture", "time","mse", "rmse", "mape", "mae"])

for cluster_number, users_in_cluster in cluster_users.items():
    #print(f"Cluster {cluster_number}:")
    
    cluster = f"cluster_{cluster_number}"
    architecture = df_evaluation["architecture"][0]
    time = 0
    mse = 0
    rmse = 0
    mape = 0
    mae = 0
    
    # Filter and print the users in the current cluster
    for user_index in users_in_cluster:
        time += df_evaluation["train_time"][user_index-1]
        mse += df_evaluation["mse"][user_index-1]
        mae += df_evaluation["mae"][user_index-1]
        rmse += df_evaluation["rmse"][user_index-1]
        mape += df_evaluation["mape"][user_index-1]
        
    num_users_in_cluster = len(users_in_cluster)
    new_row = {
        'cluster': cluster,
        'architecture': architecture, 
        'time' : time / num_users_in_cluster,
        'mse': mse / num_users_in_cluster,
        "rmse" : rmse / num_users_in_cluster,
        "mape": mape / num_users_in_cluster,
        'mae':  mae / num_users_in_cluster,
    }
    df_results.loc[len(df_results)] = new_row
    
df_results

Architecture:  L2_U8
Mean train time epoch:  2.2434112349183035
Mean mse:  0.02002903907042406
Mean mae:  0.0872910367531908

In [ ]:
#dense_results.to_csv(f'evaluations/clustered_federated_learning/{dense_architecture}.csv')
#dense_results